### ISSUE TITLE
Some package names returned by RPM does not match with the name of repository. 

### ISSUE THREAD

**Issue by hrnciar** [hrnciar/setuptools-package-reporter#3]
~~~~
Cloning into 'libsigrokdecode-devel'...
No such repository
fatal: Could not read from remote repository.
~~~~

Some package names returned by RPM does not match with the name of repository. In this case without "-devel". Find a way how to get the proper name of the package.

**Comment by hroncok** [comment]
You should only check BuildRequires. In repoquery terms, you only care about packages with `src` architecture. Such packages will never have this issue.
